version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - pip install requests -t .
      - pip install aws_xray_sdk -t .
      - pwd
      - ls -la
      - export BUCKET=rtt-audit-lambda-function
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml --debug
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  type: zip
  files:
    - 'src/audit.py'
    - 'src/common.py'
    - 'template.yaml'
    - 'outputtemplate.yaml'

