AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: audit
      Handler: audit.handler
      CodeUri: ./src
      Runtime: python3.7
      Timeout: 900
      Events:
        Type: Schedule
        Properties:
          Schedule: cron(0 21 ? * * *)
