AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:

  SnsTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: tennis.smith@roundtower.com
          Protocol: email
      TopicName: alarm-on-audit-lambda-error-action

  ServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: audit
      Handler: audit.handler
      CodeUri: ./
      Runtime: python3.7
      Timeout: 900
      Role: 'arn:aws:iam::375301133253:role/lambda_aws_audit_execution_role'
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref SnsTopic
      Events:
        SetAuditTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(0 21 ? * * *)
