AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: audit.handler
      CodeUri: 's3://rtt-audit-lambda-function'
      Runtime: python3.7
      Timeout: 900
