AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:

  SnsTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: tennis.smith@roundtower.com
          Protocol: email
      TopicName: alarm-action

  ServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: audit
      Handler: audit.handler
      CodeUri: ./
      Runtime: python3.7
      Timeout: 900
      Role: 'arn:aws:iam::375301133253:role/lambda_aws_audit_execution_role'
      Events:
        SetAuditTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(0 21 ? * * *)

  CloudWatchFunction:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "AuditFunctionErrors"
      AlarmDescription: "Alarm if lambda errors out too many times"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
        - Name: "FunctionName"
          Value: "audit"
      Statistic: "Sum"
      ComparisonOperator: "GreaterThanThreshold"
      Threshold: 0
      EvaluationPeriods: 5
      Period: 60
      TreatMissingData: "ignore"
      AlarmActions:
        - Ref: SnsTopic